In [1]:
v = list(range(1, 6))
v
2 * v
import numpy as np
v = np.arange(1, 6)
v
2 * v

array([ 2,  4,  6,  8, 10])

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c


array([ 4, 10, 18])

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a.shape
a.ndim
a.dtype.name

'int64'

In [4]:
import numpy as np
a = np.array([1,2,3,4,5])

In [5]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [10]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [7]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])

In [8]:
import pandas as pd
df = pd.DataFrame({"a": [4, 5, 6],
"b": [7, 8, 9],
"c": [10, 11, 12]},
index = [1, 2, 3])

In [11]:
type(df)


pandas.core.frame.DataFrame

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported


In [13]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [14]:
dates = pd.date_range('20181001',
periods=6)
dates


DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [15]:
df = pd.DataFrame(np.random.randn(6,4),
index=dates, columns=list('ABCD'))
df

A         B         C         D
2018-10-01 -2.991022 -1.455479 -0.538079  0.568227
2018-10-02 -0.016430  0.321620  0.765240  0.265672
2018-10-03 -1.280843  0.649028 -1.965369 -1.249372
2018-10-04 -1.377429 -0.752501 -0.702987 -0.569209
2018-10-05 -0.006494 -1.678719 -1.062572  0.779991
2018-10-06  0.289898 -0.297453  1.675349  0.688459

In [16]:
df = pd.DataFrame(np.random.randn(3,5),
index=['student1','student2','student3']
, columns=list('ABCDE'))
df

A         B         C         D         E
student1 -0.976147 -0.619366 -0.783696  0.297098  0.035196
student2 -1.098574  1.615265  0.772627 -0.812334 -0.836499
student3  0.194796 -1.379305  1.656116 -0.370026 -1.011155

In [17]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20181001'),
'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [18]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [19]:
! pip install pandas_datareader

In [20]:
conda install pandas-datareader

Jupyter detected...
3 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - defaults
Platform: win-64
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\miniconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB
    bottleneck-1.4.2           |  py313h2cb717b_0         145 KB
    intel-openmp-2025.0.0      |    haa95532_1164         2.1 MB
    libxslt-1.1.41             |       h0739af5_0         467 KB
    lxml-5.3.0                 |  py313h395c83e_1         1.1 MB
    mkl-2025.0.0               |     h5da7b33_930       104.7 MB
    mkl-service-2.4.0          |  py313h827c3e9_3          64 KB
    mkl_fft-1.3.11             |  py313h5810407_1         188 KB
    mkl_random-1.2.8           |  py313hedd7022_1         280 KB
  